package com.nebulaiq.assignment.presentation.theme

import androidx.compose.ui.graphics.Color

// Core roles from the supplied Material Theme Builder export.
val PrimaryLight = Color(0xFF6D5E0F)
val OnPrimaryLight = Color(0xFFFFFFFF)
val PrimaryContainerLight = Color(0xFFF8E287)
val OnPrimaryContainerLight = Color(0xFF534600)
val SecondaryLight = Color(0xFF665E40)
val OnSecondaryLight = Color(0xFFFFFFFF)
val SecondaryContainerLight = Color(0xFFEEE2BC)
val OnSecondaryContainerLight = Color(0xFF4E472A)
val TertiaryLight = Color(0xFF43664E)
val OnTertiaryLight = Color(0xFFFFFFFF)
val TertiaryContainerLight = Color(0xFFC5ECCE)
val OnTertiaryContainerLight = Color(0xFF2C4E38)
val ErrorLight = Color(0xFFBA1A1A)
val OnErrorLight = Color(0xFFFFFFFF)
val ErrorContainerLight = Color(0xFFFFDAD6)
val OnErrorContainerLight = Color(0xFF93000A)
val BackgroundLight = Color(0xFFFFF9EE)
val OnBackgroundLight = Color(0xFF1E1B13)
val SurfaceLight = Color(0xFFFFF9EE)
val OnSurfaceLight = Color(0xFF1E1B13)
val SurfaceVariantLight = Color(0xFFEAE2D0)
val OnSurfaceVariantLight = Color(0xFF4B4739)
val OutlineLight = Color(0xFF7C7767)
val OutlineVariantLight = Color(0xFFCDC6B4)

val PrimaryDark = Color(0xFFDBC66E)
val OnPrimaryDark = Color(0xFF3A3000)
val PrimaryContainerDark = Color(0xFF534600)
val OnPrimaryContainerDark = Color(0xFFF8E287)
val SecondaryDark = Color(0xFFD1C6A1)
val OnSecondaryDark = Color(0xFF363016)
val SecondaryContainerDark = Color(0xFF4E472A)
val OnSecondaryContainerDark = Color(0xFFEEE2BC)
val TertiaryDark = Color(0xFFA9D0B3)
val OnTertiaryDark = Color(0xFF143723)
val TertiaryContainerDark = Color(0xFF2C4E38)
val OnTertiaryContainerDark = Color(0xFFC5ECCE)
val ErrorDark = Color(0xFFFFB4AB)
val OnErrorDark = Color(0xFF690005)
val ErrorContainerDark = Color(0xFF93000A)
val OnErrorContainerDark = Color(0xFFFFDAD6)
val BackgroundDark = Color(0xFF15130B)
val OnBackgroundDark = Color(0xFFE8E2D4)
val SurfaceDark = Color(0xFF15130B)
val OnSurfaceDark = Color(0xFFE8E2D4)
val SurfaceVariantDark = Color(0xFF4B4739)
val OnSurfaceVariantDark = Color(0xFFCDC6B4)
val OutlineDark = Color(0xFF969080)
val OutlineVariantDark = Color(0xFF4B4739)
